version: "3.9"
services:
  app-service:
    image: simrat12/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: simrat12/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET} # New!
    ports:
      - "3000:3000"