version: "3.9"
services:
  app-service:
    image: simrat12/app-service
    restart: "always"
    environment:
      AUTH_SERVICE_IP: ${AUTH_SERVICE_IP}
    ports:
      - "8000:8000"
    depends_on:
      auth-service:
        condition: service_started
  auth-service:
    image: simrat12/auth-service
    restart: "always"
    environment:
      JWT_SECRET: ${JWT_SECRET} # New!
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: "always"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local